"""empty message

Revision ID: 08a8a36c61f8
Revises: 5db0cbe43198
Create Date: 2018-06-16 11:49:52.082804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a8a36c61f8'
down_revision = '5db0cbe43198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('comment_content', sa.Text(), nullable=False),
    sa.Column('comment_parent', sa.Integer(), nullable=False),
    sa.Column('state', sa.SmallInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('_create_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'tb_resources_relationships', 'tb_postmeta', ['object_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tb_resources_relationships', 'tb_resources', ['resources_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tb_role_admin', 'tb_admin', ['admin_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tb_role_admin', 'tb_role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tb_term_relationships', 'tb_postmeta', ['object_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tb_term_relationships', 'tb_term_taxonomy', ['term_taxonomy_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_term_relationships', type_='foreignkey')
    op.drop_constraint(None, 'tb_term_relationships', type_='foreignkey')
    op.drop_constraint(None, 'tb_role_admin', type_='foreignkey')
    op.drop_constraint(None, 'tb_role_admin', type_='foreignkey')
    op.drop_constraint(None, 'tb_resources_relationships', type_='foreignkey')
    op.drop_constraint(None, 'tb_resources_relationships', type_='foreignkey')
    op.drop_table('tb_comment')
    # ### end Alembic commands ###
