"""empty message

Revision ID: 8418a0625a01
Revises: f01cd8cfe60f
Create Date: 2018-06-14 10:53:43.524094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8418a0625a01'
down_revision = 'f01cd8cfe60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('link', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'tb_resources_relationships', 'tb_postmeta', ['object_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tb_resources_relationships', 'tb_resources', ['resources_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tb_role_admin', 'tb_admin', ['admin_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tb_role_admin', 'tb_role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tb_term_relationships', 'tb_postmeta', ['object_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tb_term_relationships', 'tb_term_taxonomy', ['term_taxonomy_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_term_relationships', type_='foreignkey')
    op.drop_constraint(None, 'tb_term_relationships', type_='foreignkey')
    op.drop_constraint(None, 'tb_role_admin', type_='foreignkey')
    op.drop_constraint(None, 'tb_role_admin', type_='foreignkey')
    op.drop_constraint(None, 'tb_resources_relationships', type_='foreignkey')
    op.drop_constraint(None, 'tb_resources_relationships', type_='foreignkey')
    op.drop_table('tb_link')
    # ### end Alembic commands ###
