"""empty message

Revision ID: c8447e1a81e3
Revises: 
Create Date: 2018-06-10 20:03:13.280622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8447e1a81e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_name', sa.String(length=100), nullable=False),
    sa.Column('_password', sa.String(length=100), nullable=False),
    sa.Column('img', sa.String(length=100), nullable=False),
    sa.Column('account', sa.String(length=32), nullable=False),
    sa.Column('sex', sa.SmallInteger(), nullable=False),
    sa.Column('state', sa.SmallInteger(), nullable=False),
    sa.Column('_last_time', sa.Integer(), nullable=False),
    sa.Column('_create_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account')
    )
    op.create_table('tb_config_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k', sa.String(length=50), nullable=False),
    sa.Column('v', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('prompt', sa.String(length=250), nullable=False),
    sa.Column('sorts', sa.Integer(), nullable=False),
    sa.Column('state', sa.SmallInteger(), nullable=False),
    sa.Column('texttype', sa.String(length=100), nullable=False),
    sa.Column('textvalue', sa.String(length=100), nullable=False),
    sa.Column('_create_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.String(length=32), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('log_detail', sa.Text(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('_create_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_postmeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_key', sa.String(length=256), nullable=False),
    sa.Column('meta_value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_postmeta_meta_key'), 'tb_postmeta', ['meta_key'], unique=False)
    op.create_index(op.f('ix_tb_postmeta_meta_value'), 'tb_postmeta', ['meta_value'], unique=False)
    op.create_table('tb_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_author', sa.Integer(), nullable=False),
    sa.Column('_create_time', sa.Integer(), nullable=False),
    sa.Column('post_content', sa.Text(), nullable=False),
    sa.Column('post_title', sa.String(length=256), nullable=False),
    sa.Column('post_excerpt', sa.String(length=500), nullable=False),
    sa.Column('post_status', sa.SmallInteger(), nullable=False),
    sa.Column('comment_status', sa.SmallInteger(), nullable=False),
    sa.Column('post_name', sa.String(length=256), nullable=False),
    sa.Column('_update_time', sa.Integer(), nullable=False),
    sa.Column('menu_order', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_posts_post_author'), 'tb_posts', ['post_author'], unique=False)
    op.create_index(op.f('ix_tb_posts_post_name'), 'tb_posts', ['post_name'], unique=False)
    op.create_index(op.f('ix_tb_posts_post_title'), 'tb_posts', ['post_title'], unique=False)
    op.create_table('tb_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_name', sa.String(length=256), nullable=False),
    sa.Column('new_name', sa.String(length=256), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_resources_new_name'), 'tb_resources', ['new_name'], unique=False)
    op.create_index(op.f('ix_tb_resources_old_name'), 'tb_resources', ['old_name'], unique=False)
    op.create_table('tb_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('role_type', sa.SmallInteger(), nullable=False),
    sa.Column('describe', sa.Text(), nullable=True),
    sa.Column('_role_pri', sa.Text(), nullable=True),
    sa.Column('_create_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_term_taxonomy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('taxonomy', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=100), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('term_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_terms_name'), 'tb_terms', ['name'], unique=False)
    op.create_index(op.f('ix_tb_terms_slug'), 'tb_terms', ['slug'], unique=False)
    op.create_table('tb_resources_relationships',
    sa.Column('resources_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['tb_postmeta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resources_id'], ['tb_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resources_id', 'object_id')
    )
    op.create_table('tb_role_admin',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['tb_admin.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['tb_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'admin_id')
    )
    op.create_table('tb_term_relationships',
    sa.Column('term_taxonomy_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['tb_postmeta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_taxonomy_id'], ['tb_term_taxonomy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('term_taxonomy_id', 'object_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_term_relationships')
    op.drop_table('tb_role_admin')
    op.drop_table('tb_resources_relationships')
    op.drop_index(op.f('ix_tb_terms_slug'), table_name='tb_terms')
    op.drop_index(op.f('ix_tb_terms_name'), table_name='tb_terms')
    op.drop_table('tb_terms')
    op.drop_table('tb_term_taxonomy')
    op.drop_table('tb_role')
    op.drop_index(op.f('ix_tb_resources_old_name'), table_name='tb_resources')
    op.drop_index(op.f('ix_tb_resources_new_name'), table_name='tb_resources')
    op.drop_table('tb_resources')
    op.drop_index(op.f('ix_tb_posts_post_title'), table_name='tb_posts')
    op.drop_index(op.f('ix_tb_posts_post_name'), table_name='tb_posts')
    op.drop_index(op.f('ix_tb_posts_post_author'), table_name='tb_posts')
    op.drop_table('tb_posts')
    op.drop_index(op.f('ix_tb_postmeta_meta_value'), table_name='tb_postmeta')
    op.drop_index(op.f('ix_tb_postmeta_meta_key'), table_name='tb_postmeta')
    op.drop_table('tb_postmeta')
    op.drop_table('tb_log')
    op.drop_table('tb_config_field')
    op.drop_table('tb_admin')
    # ### end Alembic commands ###
