"""empty message

Revision ID: cf66c13e272b
Revises: 3e8ae0589eb7
Create Date: 2018-06-02 17:10:37.630012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf66c13e272b'
down_revision = '3e8ae0589eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_config_field', sa.Column('state', sa.SmallInteger(), nullable=False))
    op.drop_column('tb_config_field', 'status')
    op.create_foreign_key(None, 'tb_role_admin', 'tb_role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tb_role_admin', 'tb_admin', ['admin_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_role_admin', type_='foreignkey')
    op.drop_constraint(None, 'tb_role_admin', type_='foreignkey')
    op.add_column('tb_config_field', sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False))
    op.drop_column('tb_config_field', 'state')
    # ### end Alembic commands ###
