"""empty message

Revision ID: f44997ff6144
Revises: 53ab2f83cdcf
Create Date: 2018-06-02 15:27:10.201967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44997ff6144'
down_revision = '53ab2f83cdcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_config_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('v', sa.Text(), nullable=True),
    sa.Column('k', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('prompt', sa.String(length=250), nullable=False),
    sa.Column('sorts', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('texttype', sa.String(length=100), nullable=False),
    sa.Column('textvalue', sa.String(length=100), nullable=False),
    sa.Column('_create_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.String(length=32), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('log_detail', sa.String(length=128), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('_create_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'tb_role_admin', 'tb_role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tb_role_admin', 'tb_admin', ['admin_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_role_admin', type_='foreignkey')
    op.drop_constraint(None, 'tb_role_admin', type_='foreignkey')
    op.drop_table('tb_log')
    op.drop_table('tb_config_field')
    # ### end Alembic commands ###
