"""empty message

Revision ID: f62f3deaddf5
Revises: 
Create Date: 2018-06-08 17:17:55.193382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62f3deaddf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_author', sa.Integer(), nullable=False),
    sa.Column('_create_time', sa.Integer(), nullable=False),
    sa.Column('post_content', sa.Text(), nullable=False),
    sa.Column('post_title', sa.String(length=256), nullable=False),
    sa.Column('post_excerpt', sa.String(length=500), nullable=False),
    sa.Column('post_status', sa.SmallInteger(), nullable=False),
    sa.Column('comment_status', sa.SmallInteger(), nullable=False),
    sa.Column('post_name', sa.String(length=256), nullable=False),
    sa.Column('_update_time', sa.Integer(), nullable=False),
    sa.Column('menu_order', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_posts_post_author'), 'tb_posts', ['post_author'], unique=False)
    op.create_index(op.f('ix_tb_posts_post_name'), 'tb_posts', ['post_name'], unique=False)
    op.create_index(op.f('ix_tb_posts_post_title'), 'tb_posts', ['post_title'], unique=False)
    op.create_table('tb_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('old_name', sa.String(length=256), nullable=False),
    sa.Column('new_name', sa.String(length=256), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_resources_new_name'), 'tb_resources', ['new_name'], unique=False)
    op.create_index(op.f('ix_tb_resources_old_name'), 'tb_resources', ['old_name'], unique=False)
    op.create_table('tb_term_taxonomy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('taxonomy', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=100), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('term_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_terms_name'), 'tb_terms', ['name'], unique=False)
    op.create_index(op.f('ix_tb_terms_slug'), 'tb_terms', ['slug'], unique=False)
    op.create_table('tb_resources_relationships',
    sa.Column('resources_id', sa.Integer(), nullable=False),
    sa.Column('posts_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['posts_id'], ['tb_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resources_id'], ['tb_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resources_id', 'posts_id')
    )
    op.create_table('tb_term_relationships',
    sa.Column('term_taxonomy_id', sa.Integer(), nullable=False),
    sa.Column('posts_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['posts_id'], ['tb_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_taxonomy_id'], ['tb_term_taxonomy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('term_taxonomy_id', 'posts_id')
    )
    op.create_foreign_key(None, 'tb_role_admin', 'tb_admin', ['admin_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tb_role_admin', 'tb_role', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_role_admin', type_='foreignkey')
    op.drop_constraint(None, 'tb_role_admin', type_='foreignkey')
    op.drop_table('tb_term_relationships')
    op.drop_table('tb_resources_relationships')
    op.drop_index(op.f('ix_tb_terms_slug'), table_name='tb_terms')
    op.drop_index(op.f('ix_tb_terms_name'), table_name='tb_terms')
    op.drop_table('tb_terms')
    op.drop_table('tb_term_taxonomy')
    op.drop_index(op.f('ix_tb_resources_old_name'), table_name='tb_resources')
    op.drop_index(op.f('ix_tb_resources_new_name'), table_name='tb_resources')
    op.drop_table('tb_resources')
    op.drop_index(op.f('ix_tb_posts_post_title'), table_name='tb_posts')
    op.drop_index(op.f('ix_tb_posts_post_name'), table_name='tb_posts')
    op.drop_index(op.f('ix_tb_posts_post_author'), table_name='tb_posts')
    op.drop_table('tb_posts')
    # ### end Alembic commands ###
